// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtZh-8NY8Kzl9nMOjf954__TN54_7rog',
    appId: '1:291752603937:web:ed172312ecd610c8acce60',
    messagingSenderId: '291752603937',
    projectId: 'mimercado-33616',
    authDomain: 'mimercado-33616.firebaseapp.com',
    storageBucket: 'mimercado-33616.firebasestorage.app',
    measurementId: 'G-4LK2437E0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxkJMW62VUqxaM9EuGxJFcc-icuJZUzDU',
    appId: '1:291752603937:android:30eb10cd29f27667acce60',
    messagingSenderId: '291752603937',
    projectId: 'mimercado-33616',
    storageBucket: 'mimercado-33616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBweuPLQvmduGvngFilrTVLsJY6lbmKAOM',
    appId: '1:291752603937:ios:a58f12a977cb8e18acce60',
    messagingSenderId: '291752603937',
    projectId: 'mimercado-33616',
    storageBucket: 'mimercado-33616.firebasestorage.app',
    iosBundleId: 'com.example.miMercado',
  );
}
